name: release-docker-unstable
on:
  push:
    branches:
    - main
jobs:
  deploy-docker-unstable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ledongthuc/awssecretsmanagerui:latest
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push
      run: docker push ledongthuc/awssecretsmanagerui:unstable
