name: release-docker
on:
  release:
    types: [published]
jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Set release version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ledongthuc/awssecretsmanagerui:latest
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push latest
      run: docker push ledongthuc/awssecretsmanagerui:latest
    - name: Push version
      run: docker push ledongthuc/awssecretsmanagerui:${{ steps.vars.outputs.tag }}
